-- MySQL Script generated by MySQL Workbench
-- Sat Jul 27 09:58:47 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

#drop database baseDS;
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `baseDS` DEFAULT CHARACTER SET utf8 ;
USE `baseDS` ;

-- -----------------------------------------------------
-- Table `mydb`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseDS`.`Estado` (
  `idEstado` INT NOT NULL auto_increment,
  `nombreEstado` VARCHAR(25) NOT NULL,
  `numEstado` INT NOT NULL,
  `zona` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseDS`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(15) NOT NULL,
  `contra` VARCHAR(10) NOT NULL,
  `tipo` VARCHAR(15) NOT NULL,
  `Estado_idEstado` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `Estado_idEstado`),
  INDEX `fk_Usuario_Estado1_idx` (`Estado_idEstado` ASC) ,
  CONSTRAINT `fk_Usuario_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `baseDS`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

#select *from Usuario;

-- -----------------------------------------------------
-- Table `mydb`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseDS`.`Proveedor` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `RFC` VARCHAR(13) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto_inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseDS`.`Producto_inventario` (
  `idProducto_inventario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `cantidad` TINYINT(4) NOT NULL,
  `porcion` FLOAT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `fecha_elaboracion` DATE NOT NULL,
  `fecha_vencimiento` DATE NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Proveedor_idProveedor` INT NOT NULL,
  `precio` FLOAT NOT NULL,
  PRIMARY KEY (`idProducto_inventario`, `Usuario_idUsuario`, `Proveedor_idProveedor`),
  INDEX `fk_Producto_inventario_Usuario1_idx` (`Usuario_idUsuario` ASC) ,
  INDEX `fk_Producto_inventario_Proveedor1_idx` (`Proveedor_idProveedor` ASC) ,
  CONSTRAINT `fk_Producto_inventario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `baseDS`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_inventario_Proveedor1`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `baseDS`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseDS`.`Cliente` (
  `idCliente` INT NOT NULL auto_increment,
  `Usuario_idUsuario` INT NOT NULL,
  `rfc` VARCHAR(13) NOT NULL,
  `direccion` VARCHAR(30) NOT NULL,
  `nombreEstablecimiento` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idCliente`, `Usuario_idUsuario`),
  INDEX `fk_Cliente_Usuario1_idx` (`Usuario_idUsuario` ASC) ,
  CONSTRAINT `fk_Cliente_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `baseDS`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseDS`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `total` FLOAT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `Cliente_idCliente`),
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente_idCliente` ASC) ,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `baseDS`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DetallePedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseDS`.`DetallePedido` (
  `idDetallePedido` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Pedido_Usuario_idUsuario` INT NOT NULL,
  `Producto_inventario_idProducto_inventario` INT NOT NULL,
  PRIMARY KEY (`idDetallePedido`, `Pedido_idPedido`, `Pedido_Usuario_idUsuario`, `Producto_inventario_idProducto_inventario`),
  INDEX `fk_DetallePedido_Pedido1_idx` (`Pedido_idPedido` ASC, `Pedido_Usuario_idUsuario` ASC) ,
  INDEX `fk_DetallePedido_Producto_inventario1_idx` (`Producto_inventario_idProducto_inventario` ASC) ,
  CONSTRAINT `fk_DetallePedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `baseDS`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetallePedido_Producto_inventario1`
    FOREIGN KEY (`Producto_inventario_idProducto_inventario`)
    REFERENCES `baseDS`.`Producto_inventario` (`idProducto_inventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;